### ISSUE TITLE
Cytryny

### ISSUE THREAD

**Issue by szydell** [axesider/arkadia-oswajanie#1]
> oswajaj zwierze cytryna

Karmiac Ulricha kawalkiem cytryny(?) zachecasz go do wspolnej zabawy i nauki sztuczek, by wzmocnic w ten sposob laczaca was wiez.

**Comment by szydell** [comment]
Jednak nie tylko cytryny.

> oswajaj zwierze sliwka
Karmiac Ulricha kawalkiem sliwki(?) zachecasz go do wspolnej zabawy i nauki sztuczek, by wzmocnic w ten sposob laczaca was wiez.

**Comment by axesider** [comment]
Doszło "kawalkiem"

**Comment by szydell** [comment]
No nie tylko, bo jest inny przypadek jeszcze.

Karmiac Ulricha kawalkiem papai(?) zachecasz go do wspolnej zabawy i nauki sztuczek, by wzmocnic w ten sposob laczaca was wiez.
Nie wiem co to 'papai'

**Comment by axesider** [comment]
Na razie dodalem tylko szczatki. Reszta wkrotce

**Comment by axesider** [comment]
Powinno juz dzialac
