### ISSUE TITLE
Marchew, winogrona

### ISSUE THREAD

**Issue by ghost** [axesider/arkadia-oswajanie#4]
Póki co u mnie takie braki wyskoczyły.

Masz przy sobie zielonkawe winogrona.

Karmiac Lukiera kawalkiem winogron(?) zachecasz go do wspolnej zabawy i nauki sztuczek, by wzmocnic
w ten sposob laczaca was wiez.
Nie ma w bazie '' 

Masz przy sobie czerwona marchew.

Karmiac Lukiera kawalkiem marchwi(?) zachecasz go do wspolnej zabawy i nauki sztuczek, by wzmocnic w
ten sposob laczaca was wiez.
Nie ma w bazie ''

Masz przy sobie czerwony podluzny owoc.

Karmiac Lukiera kawalkiem owocu(?) zachecasz go do wspolnej zabawy i nauki sztuczek, by wzmocnic w
ten sposob laczaca was wiez.
Nie ma w bazie ''

**Comment by axesider** [comment]
Poprawione

**Comment by axesider** [comment]
Poprawione
