### ISSUE TITLE
Wywalenie slowa 'kawalkiem'

### ISSUE THREAD

**Issue by mwarzec** [axesider/arkadia-oswajanie#9]
Całkowicie zbędne jest te 'kawalkiem. Trigger wyłapujacy powinien być poprawiony aby ignorowalo jak wystapi.

![image](https://github.com/axesider/arkadia-oswajanie/assets/62749025/77354ef9-111f-4055-b1e8-a352c3e1f1fa)

**Comment by axesider** [comment]
Chyba nie do konca, bo mozna 'miesem x' i 'kawalkiem miesa x'

**Comment by szydell** [comment]
Chyba chodzi o kolumnę 'zwierzę'. Tam jest niepotrzebne.
Chociaż to ciekawe, bo u mnie takiego problemu nie ma (zwierzę ma imię).

**Comment by axesider** [comment]
Bazy nie poprawię, polecam do tego https://sqlitebrowser.org/
